### PR TITLE
Parse lower/mixed case input files

### PR DESCRIPTION
**Pull request by benzwick**
Abaqus input files are case insensitive.

Previously, the element type (e.g. C3D4 == c3d4)
and the NSET and ELSET options were not recognized
if lower or mixed case.

Note: Boundary conditions and loads are read verbatim
(i.e. symbols :P or :p are created for pressure loads
depending on the case used in the input file)
which may cause confusion.

### CODE REVIEW

**Comment by ahojukka5** [comment]
LGTM, thanks a lot for this contribution also.

**Comment by avigliotti** [comment]
Hi, 
thanks for the great work! 

would it possible to add an option that prevents the verbose info outputs when reading a model or a mesh?

**Comment by benzwick** [comment]
> Hi,
> thanks for the great work!
> 
> would it possible to add an option that prevents the verbose info outputs when reading a model or a mesh?

See issue #45

**Comment by avigliotti** [comment]
just saw it, thanks

**Pull request merged**
