### PR TITLE
Add mesh reader test for trusses

### PR DESCRIPTION
**Pull request by jtveiten**
The mesh part is now read. Need to do the model part later, keyword density isn't recognized yet

### CODE REVIEW

**Comment by ahojukka5** [comment]
We are not sure if it is ok to add that test file into the repository, it probably is copyrighted by Dassault. I implemented a new function `download_abaqus` which can be used to download files on the fly before testing, requiring that one has set `ABAQUS_DOWNLOAD_URL` to point someplace where the files can be downloaded.

Could you do the following changes:
- rebase from newest master to get `download_abaqus`
- remove file `et22sfse.inp` from repository
- use `fn = abaqus_download("et22sfse.inp")` to download the file from a some secret place during the testing, where `fn` is the full path to the downloaded file.

You don't have to set `ABAQUS_DOWNLOAD_URL`, it's already set on Travis CI configuration of the repository. Also, consider squashing changes to keep version history clean. This also prevents the file `et22sfse.inp` from being written into the repository at any point. [Here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) is a quite good explanation how squashing works.

**Comment by ahojukka5** [comment]
Looks that my test is breaking further tests. I have to fix it.

**Comment by jtveiten** [comment]
First of all, apologies for not looking at the terms and conditions.
I have done the changes, but I wasn't sure I got the squashing right after some trys, so I haven't done that yet.
The test runs locally on my machine as far as I can see?

**Comment by ahojukka5** [comment]
It was another test messing up environment variables and not returning the original state. If you now rebase again for newest master this should work.

**Comment by jtveiten** [comment]
If I run it locally after setting the env. variable, including the reader and including runtests.jl, it seems to succeed. But if do an include("runtests.jl") again, it fails

**Comment by ahojukka5** [comment]
One more time, rebase for the newest master.

**Comment by ahojukka5** [comment]
Hmm https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

**Comment by jtveiten** [comment]
Do I need to protect the test by checking for an empty string returned from abaqus_download?
This will work once it the code is in master?

**Comment by ahojukka5** [comment]
Well the test probably should work, it branch is under JuliaFEM/AbaqusReader.jl, let see what happens when I opened a new PR based on this change. PR #32.

**Comment by jtveiten** [comment]
So that worked. But it is unfortunate that the forks don't build.

**Comment by ahojukka5** [comment]
Ok this is now merged in PR #32.

**Comment by ahojukka5** [comment]
Yes, but there is a good reason why environment variables are not set for pull requests coming outside of the organization. Someone could do something like `println(ENV["PASSWORD"])` and then read the output from Travis CI log...

**Pull request closed without merging**
